# adapted from http://conda.pydata.org/docs/travis.html
language: python
python:
 # We don't actually use the Travis Python, but this keeps it organized.
 - "2.7"
 - "3.5"

# switch to new infrastructure
sudo: false

before_install:
 # download and install miniconda
 - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/conda
 - export PATH="$HOME/conda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 # Useful for debugging any issues with conda
 - conda info -a

 # create and activate the build/test environment
 - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
 - source activate tenv

# additional .debs we need:
addons:
 apt:
  packages:
    - build-essential
    - openjdk-7-jdk
    - swig
    - libjpeg-dev

install:
 - conda install -q scikit-learn numpy pillow pandas jupyter nbconvert matplotlib seaborn

 # install the most recent rdkit package from the RDKit anaconda channel.
 - conda install -q -c rdkit rdkit

before_script:
 # RDKit
 - export RDBASE=$CONDA_PREFIX/Library/share/RDKit
 - echo $RDBASE

script:
 - export BASEDIR=`pwd`
 - cd notebooks
 - python ../testing/run_tests.py *.ipynb
